version: '2'

services: 
    # nginx:
    #     container_name: nginx
    #     image: nginxapp
    #     volumes: 
    #         - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    #     ports: 
    #         - "8888:80"
    #     restart: always
    #     networks: 
    #         - application-network

    go-course:
        image: docker.io/library/courseimage
        ports: 
            - "9090:9090"
        networks: 
            - application-network

    go-user:
        image: docker.io/library/userimg
        ports: 
            - "9091:9091"
        networks: 
            - application-network

networks: 
    application-network:
        name: "application-network"